### PR TITLE
put links accessible for model and collection for future use

### PR DESCRIPTION
**Pull request by Aimage**
I was searching for a simple way to implement link parsing.
And I think the best and simplest way to do it is by using handle function like we do with meta (handleMeta).
This is an implementation of this concept with a default function called handleLinks for RelationalModel and Collection. User can customise it with his custom function but at least we provide a default implementation that can be useful.

Data for testing:
```javascript
{
  "type": "articles",
  "id": "1",
  "attributes": {
    "title": "Rails is Omakase"
  },
  "relationships": {
    "author": {
      "links": {
        "self": "http://example.com/articles/1/relationships/author",
        "related": { "href": "http://example.com/articles/1/author",
                       "meta": {
                                  "count": 10
                                  }
                       }
      },
      "data": { "type": "people", "id": "9" }
    }
  },
  "links": {
    "self": "http://example.com/articles/1"
  }
}
```

### CODE REVIEW

**Comment by xbill82** [comment]
I am no longer maintaining this repo, how can I pass it to you?

**Comment by Aimage** [comment]
No problem. Perhaps I can continue with the fork. I don't know if there is a better way.
And if you can give some advice for the build and everything around the repository.

**Comment by xbill82** [comment]
Honestly, I made this sooooo much time ago I don't remember a single thing. 
What kind of advice would you need? I should close this repo once our conversation is over.

**Comment by Aimage** [comment]
I would like to know about release. Ho do you manage to make the release and with what tools?
And also how to publish on https://www.npmjs.com cause I see that it's also apear on this site.
Perhaps a link that explain basics.
I'm a newbie with github process and JavaScript library.

**Comment by xbill82** [comment]
I never released this on NPM, as you can read in the README.md at the root, I did publish it on Bower, which is deprecated nowadays.
If you want to publish this package to NPM, follow the instructions [here](https://docs.npmjs.com/packages-and-modules/contributing-packages-to-the-registry).

**Comment by Aimage** [comment]
Thank you. Maybe I'll ask you some question in futur but I thing that's enough to start.
I'll merge this branch to my master.

**Pull request closed without merging**
